import { createHash } from "node:crypto";
import {
  createMcpHandler,
  Server,
  type CallToolResult,
  type Tool,
} from "@modelcontextprotocol/server";
import { z } from "zod";
import { toNodeHandler } from "@modelcontextprotocol/node";
import {
  IdSchema,
  PermissionLevelSchema,
  EngineeringPlanSchema,
} from "@aegisforge/contracts";
import type { EngineeringPlan } from "@aegisforge/contracts";
import { selectAgent } from "@aegisforge/controller";
import type { PlatformStore } from "../domain.js";
import type { TaskRunner } from "../task-runner.js";

const tools: Tool[] = [
  {
    name: "aegis_list_agents",
    description: "List AegisForge Agents and their current status.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
  },
  {
    name: "aegis_list_projects",
    description: "List registered AegisForge Projects.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
  },
  {
    name: "aegis_list_approvals",
    description: "List pending and recent operation approvals.",
    inputSchema: {
      type: "object",
      properties: {},
      additionalProperties: false,
    },
  },
  {
    name: "aegis_create_task",
    description:
      "Create an automatically or explicitly assigned engineering task. Mutations require a caller-stable idempotencyKey.",
    inputSchema: {
      type: "object",
      required: [
        "idempotencyKey",
        "projectId",
        "goal",
      ],
      additionalProperties: false,
      properties: {
        idempotencyKey: { type: "string", minLength: 8, maxLength: 200 },
        projectId: { type: "string", format: "uuid" },
        agentId: { type: "string", format: "uuid" },
        workspaceId: { type: "string", format: "uuid" },
        goal: { type: "string", minLength: 3, maxLength: 20000 },
        maxFixAttempts: { type: "integer", minimum: 0, maximum: 5 },
        requiredPermissionLevel: { type: "integer", minimum: 0, maximum: 4 },
        technologies: { type: "array", maxItems: 30, items: { type: "string" } },
      },
    },
  },
  {
    name: "aegis_submit_plan",
    description:
      "Submit an EngineeringPlan generated by CustomGPT for an existing task.",
    inputSchema: {
      type: "object",
      required: [
        "taskId",
        "plan",
      ],
      additionalProperties: false,
      properties: {
        taskId: {
          type: "string",
          format: "uuid",
        },
        plan: {
          type: "object",
        },
      },
    },
  },
];
const text = (value: unknown, isError = false): CallToolResult => ({
  content: [
    {
      type: "text",
      text: typeof value === "string" ? value : JSON.stringify(value, null, 2),
    },
  ],
  ...(isError ? { isError: true } : {}),
});
const hash = (value: unknown) =>
  createHash("sha256").update(JSON.stringify(value)).digest("hex");

function serverFor(store: PlatformStore, runner?: TaskRunner | null) {
  const server = new Server(
    { name: "aegisforge", version: "0.1.0" },
    { capabilities: { tools: {} } },
  );
  server.setRequestHandler("tools/list", async () => ({ tools }));
  server.setRequestHandler("tools/call", async (request) => {
    try {
      const args = (request.params.arguments ?? {}) as Record<string, unknown>;
      switch (request.params.name) {
        case "aegis_list_agents":
          return text(await store.listAgents());
        case "aegis_list_projects":
          return text(await store.listProjects());
        case "aegis_list_approvals":
          return text(await store.listApprovals());
        case "aegis_submit_plan": {
          const input = z.object({
            taskId: IdSchema,
            plan: EngineeringPlanSchema,
          }).parse(args);

          const plan: EngineeringPlan = input.plan;

          await store.saveTaskPlan(
            input.taskId,
            plan,
          );

          if (runner) {
            void runner.run(input.taskId).catch(() => undefined);
          }

          return text({
            ok: true,
            taskId: input.taskId,
          });
        }

        case "aegis_create_task": {
          const key =
            typeof args.idempotencyKey === "string" ? args.idempotencyKey : "";
          if (key.length < 8) throw new Error("idempotencyKey is required");
          const requested = z.object({
            projectId: IdSchema,
            agentId: IdSchema.optional(),
            workspaceId: IdSchema.optional(),
            goal: z.string().trim().min(3).max(20_000),
            maxFixAttempts: z.number().int().min(0).max(5).default(2),
            requiredPermissionLevel: PermissionLevelSchema.default(2),
            technologies: z.array(z.string().min(1).max(100)).max(30).default([]),
          }).refine((value) => Boolean(value.agentId) === Boolean(value.workspaceId), { message: "agentId and workspaceId must be provided together" }).parse(args);
          let assignment: { agentId: string; workspaceId: string };
          if (requested.agentId && requested.workspaceId) assignment = { agentId: requested.agentId, workspaceId: requested.workspaceId };
          else {
            const selected = selectAgent({ projectId: requested.projectId, requiredPermissionLevel: requested.requiredPermissionLevel, technologies: requested.technologies, agents: await store.listAgents(), workspaces: await store.listWorkspaces(requested.projectId) });
            if (selected.type !== "SELECTED") throw new Error(`Agent selection required: ${JSON.stringify(selected)}`);
            assignment = selected;
          }
          const input = {
            projectId: requested.projectId,
            ...assignment,
            goal: requested.goal,
            maxFixAttempts: requested.maxFixAttempts,
          };
          const [agent, project, workspace] = await Promise.all([
            store.findAgent(input.agentId),
            store.findProject(input.projectId),
            store.findWorkspace(input.workspaceId),
          ]);
          if (
            !agent ||
            !project ||
            !workspace ||
            workspace.agentId !== agent.id ||
            workspace.projectId !== project.id
          )
            throw new Error("Invalid explicit task assignment");
          const result = await store.createTaskIdempotently(
            key,
            hash(requested),
            input,
          );
          if (result.type === "MISMATCH")
            throw new Error("Idempotency key reused with a different request");
          if (result.type === "CREATED" && runner) void runner.run(result.task.id).catch(() => undefined);
          return text(result.task);
        }
        default:
          return text("Unknown tool", true);
      }
    } catch (error) {
      return text(error instanceof Error ? error.message : String(error), true);
    }
  });
  return server;
}
export function createMcpNodeHandler(store: PlatformStore, runner?: TaskRunner | null) {
  return toNodeHandler(
    createMcpHandler(() => serverFor(store, runner), { legacy: "stateless" }),
  );
}
